# Generated by Django 4.2.7 on 2023-11-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('user', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('startTime', models.DateTimeField(auto_now_add=True)),
                ('cookieCount', models.IntegerField(default=0)),
                ('autoClickCount', models.IntegerField(default=0)),
                ('doubleClickCount', models.IntegerField(default=0)),
                ('autoClickPrice', models.IntegerField(default=20)),
                ('doubleClickPrice', models.IntegerField(default=40)),
            ],
        ),
    ]
