# Generated by Django 4.2.7 on 2023-11-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesession', '0002_remove_gamesession_farmcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='id',
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='user',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
