# Generated by Django 4.2.7 on 2023-11-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesession', '0003_remove_gamesession_id_alter_gamesession_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='endTime',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='doubleClickCount',
            field=models.IntegerField(default=0),
        ),
    ]
