# Generated by Django 4.2.7 on 2023-11-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesession', '0004_remove_gamesession_endtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='autoClickerPrice',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='doubleClickPrice',
            field=models.IntegerField(default=40),
        ),
    ]
