# Generated by Django 4.2.7 on 2023-11-22 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamesession', '0005_gamesession_autoclickerprice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamesession',
            old_name='autoClickerCount',
            new_name='autoClickCount',
        ),
        migrations.RenameField(
            model_name='gamesession',
            old_name='autoClickerPrice',
            new_name='autoClickPrice',
        ),
    ]
